### ISSUE TITLE
npm install discord.js node-imap enmap

### ISSUE THREAD

**Issue by c0d3high** [Ztassin664/-discord-email-gmail-bot#1]
Hi,
Trying to run the command npm install discord.js node-imap enmap and receiving errors

└─$ npm install discord.js node-imap enmap
npm ERR! code 1
npm ERR! path /mnt/c/WINDOWS/system32/DiscordGmailBot/node_modules/better-sqlite3
npm ERR! command failed
npm ERR! command sh -c prebuild-install || npm run build-release
npm ERR! > better-sqlite3@7.4.5 build-release
npm ERR! > node-gyp rebuild --release
npm ERR!
npm ERR! make: Entering directory '/mnt/c/WINDOWS/system32/DiscordGmailBot/node_modules/better-sqlite3/build'
npm ERR!   TOUCH b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
npm ERR!   ACTION deps_sqlite3_gyp_locate_sqlite3_target_extract_sqlite3 b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
npm ERR! rm b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
npm ERR! make: Leaving directory '/mnt/c/WINDOWS/system32/DiscordGmailBot/node_modules/better-sqlite3/build'
npm ERR! prebuild-install WARN install EPERM: operation not permitted, utime '/mnt/c/WINDOWS/system32/DiscordGmailBot/node_modules/better-sqlite3/build/Release/better_sqlite3.node'
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@12.22.7 | linux | x64
npm ERR! gyp info find Python using Python version 3.9.8 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/share/nodejs/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/mnt/c/WINDOWS/system32/DiscordGmailBot/node_modules/better-sqlite3/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/share/nodejs/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/include/nodejs/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/usr/include/nodejs',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/share/nodejs/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/usr/include/nodejs/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/mnt/c/WINDOWS/system32/DiscordGmailBot/node_modules/better-sqlite3',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! internal/process/warning.js:118
npm ERR!     throw new ERR_INVALID_ARG_TYPE('code', 'string', code);
npm ERR!     ^
npm ERR!
npm ERR! TypeError [ERR_INVALID_ARG_TYPE]: The "code" argument must be of type string. Received an instance of Error
npm ERR!     at Unpack.emitWarning (internal/process/warning.js:118:11)
npm ERR!     at Unpack.emit (events.js:314:20)
npm ERR!     at Unpack.warn (/mnt/c/WINDOWS/system32/DiscordGmailBot/node_modules/tar/lib/warn-mixin.js:15:12)
npm ERR!     at Unpack.warn (/mnt/c/WINDOWS/system32/DiscordGmailBot/node_modules/tar/lib/unpack.js:220:18)
npm ERR!     at Unpack.[onError] (/mnt/c/WINDOWS/system32/DiscordGmailBot/node_modules/tar/lib/unpack.js:343:12)
npm ERR!     at done (/mnt/c/WINDOWS/system32/DiscordGmailBot/node_modules/tar/lib/unpack.js:411:22)
npm ERR!     at /mnt/c/WINDOWS/system32/DiscordGmailBot/node_modules/tar/lib/unpack.js:439:52
npm ERR!     at FSReqCallback.oncomplete (fs.js:156:23) {
npm ERR!   code: 'ERR_INVALID_ARG_TYPE'
npm ERR! }
npm ERR! make: *** [deps/locate_sqlite3.target.mk:17: b857c92884e9598d609f6be182a2595df7a8e00f.intermediate] Error 1
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/share/nodejs/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
npm ERR! gyp ERR! System Linux 4.19.128-microsoft-standard
npm ERR! gyp ERR! command "/usr/bin/node" "/usr/share/nodejs/node-gyp/bin/node-gyp.js" "rebuild" "--release"
npm ERR! gyp ERR! cwd /mnt/c/WINDOWS/system32/DiscordGmailBot/node_modules/better-sqlite3
npm ERR! gyp ERR! node -v v12.22.7
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tmoney/.npm/_logs/2021-11-27T03_51_01_047Z-debug.log

**Comment by c0d3high** [comment]
nevermind I got it working
